#### Multi-indexing pandas dataframe

In [1]:
#Ejem 1

import pandas as pd
from IPython.core.display import HTML

dic1={
    "year":[2018,2018,2018,2019,2019,2019],
    "country":["spain","portugal","france","spain","portugal","france"]
     }

df=pd.DataFrame(dic1)
display(HTML(df.to_html()))

index=pd.MultiIndex.from_frame(df)

data=pd.DataFrame(data=[1234,5678,9012,3456,7890,1237],index=index,columns=["vaccinations"])

display(HTML(data.to_html()))

In [2]:
#Ejem 1 -> GROUPBY

import pandas as pd
from IPython.core.display import HTML

dic2={
    "year":[2018,2018,2018,2019,2019,2019],
    "country":["spain","portugal","france","spain","portugal","france"],
    "vaccinations":[1234,5678,9012,3456,7890,1237]
     }

df2=pd.DataFrame(dic2)
display(HTML(df2.to_html()))

df_g_y=df2.groupby(["year"])

for key,group in df_g_y:    
    print("+key ", key)
    print("+number ", len(group))
    print(group.head())
    print("\n")
    
    
print("_________________________________________")    

df_g_c=df2.groupby(["country"])

for key,group in df_g_c:    
    print("+key ", key)
    print("+number ", len(group))
    print(group.head())
    print("\n")

+key  2018
+number  3
   year   country  vaccinations
0  2018     spain          1234
1  2018  portugal          5678
2  2018    france          9012


+key  2019
+number  3
   year   country  vaccinations
3  2019     spain          3456
4  2019  portugal          7890
5  2019    france          1237


____________________________________________________________________________
+key  france
+number  2
   year country  vaccinations
2  2018  france          9012
5  2019  france          1237


+key  portugal
+number  2
   year   country  vaccinations
1  2018  portugal          5678
4  2019  portugal          7890


+key  spain
+number  2
   year country  vaccinations
0  2018   spain          1234
3  2019   spain          3456